[package]
name = "rust_sqlite_repr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bundled = []

[dependencies]
sqlite3-sys = "0.15.0"
sqlite = "0.30.5"
